services:
  api:
    build:
      context: ./api
    ports:
      - 3030:3000
    volumes:
      - ./api/:/rails
    environment:
      - RAILS_ENV=development
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      - db

  db:
    image: postgres:16.0
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

volumes:
  pg-data:
